import {
  computeAerodynamicOutputs,
  type AeroPerformanceTable,
} from "./aero";
import {
  createPitchControllerConfig,
  createPitchControllerState,
  stepPitchController,
  type PitchControllerConfig,
  type PitchControllerDiagnostics,
  type PitchControllerState,
} from "./controller";
import type { ControlInputs } from "./inputs";
import { computeRelativeWind, stepSimulation } from "./model";
import type { TunableParameters } from "./params";
import type { TurbineState } from "./state";
import {
  createWindDisturbance,
  getWindDisturbanceSample,
  stepWindDisturbance,
  type WindDisturbanceConfig,
  type WindDisturbanceSample,
} from "./wind";

export type SimulationControllerMode =
  | OpenLoopFixedControlMode
  | ClosedLoopPitchPiControlMode;

export interface OpenLoopFixedControlMode {
  mode: "open-loop-fixed";
  fixedControl: ControlInputs;
}

export interface ClosedLoopPitchPiControlMode {
  mode: "closed-loop-pitch-pi";
  config?: PitchControllerConfig;
  initialPitchRad?: number;
  initialControllerState?: PitchControllerState;
}

export interface SimulationInitialStateOptions {
  timeS?: number;
  rotorSpeedRadPerSec?: number;
  rotorAzimuthRad?: number;
  platformPitchRad?: number;
  platformPitchRateRadPerSec?: number;

  /**
   * Used only when platformPitchRad is omitted.
   * The default initial platform pitch is the static equilibrium
   * generated by aerodynamic thrust at this wind speed.
   */
  equilibriumWindSpeedMps?: number;

  /**
   * Used only when platformPitchRad is omitted.
   */
  equilibriumPitchRad?: number;
}

export interface SimulationScenarioConfig {
  name: string;
  totalTimeS: number;
  dtS: number;
  wind: WindDisturbanceConfig;
  controller: SimulationControllerMode;
  initialState?: SimulationInitialStateOptions;
}

export interface SimulationScenarioSample {
  timeS: number;

  windSpeedMps: number;
  meanWindSpeedMps: number;
  gustMps: number;
  turbulentMps: number;
  effectiveWindSpeedMps: number;
  projectedWindSpeedMps: number;
  platformVelocityWindCorrectionMps: number;
  rotorTiltRad: number;
  rotorNormalProjectionFactor: number;

  rotorSpeedRadPerSec: number;
  rotorAzimuthRad: number;

  collectivePitchRad: number;
  generatorTorqueNm: number;

  platformPitchRad: number;
  platformPitchRateRadPerSec: number;

  aerodynamicPowerW: number;
  aerodynamicTorqueNm: number;
  thrustN: number;
  cp: number;
  ct: number;

  wavePitchMomentNm: number;

  controllerDiagnostics?: PitchControllerDiagnostics;
}

export interface SimulationScenarioResult {
  scenario: SimulationScenarioConfig;
  samples: SimulationScenarioSample[];
  finalState: TurbineState;
}

export interface RunSimulationScenarioArgs {
  scenario: SimulationScenarioConfig;
  params: TunableParameters;
  aeroTable: AeroPerformanceTable;
}

export interface CreateScenarioArgs {
  name: string;
  totalTimeS: number;
  dtS: number;
  wind: WindDisturbanceConfig;
  params: TunableParameters;
  initialState?: SimulationInitialStateOptions;
}

export function createOpenLoopScenario(
  args: CreateScenarioArgs & {
    fixedControl?: Partial<ControlInputs>;
  },
): SimulationScenarioConfig {
  return {
    name: args.name,
    totalTimeS: args.totalTimeS,
    dtS: args.dtS,
    wind: args.wind,
    initialState: args.initialState,
    controller: {
      mode: "open-loop-fixed",
      fixedControl: {
        collectivePitchRad:
          args.fixedControl?.collectivePitchRad ?? args.params.trimPitchRad,
        generatorTorqueNm:
          args.fixedControl?.generatorTorqueNm ??
          args.params.ratedGeneratorTorqueNm,
      },
    },
  };
}

export function createClosedLoopScenario(
  args: CreateScenarioArgs & {
    controllerConfig?: PitchControllerConfig;
    initialPitchRad?: number;
  },
): SimulationScenarioConfig {
  return {
    name: args.name,
    totalTimeS: args.totalTimeS,
    dtS: args.dtS,
    wind: args.wind,
    initialState: args.initialState,
    controller: {
      mode: "closed-loop-pitch-pi",
      config: args.controllerConfig,
      initialPitchRad: args.initialPitchRad,
    },
  };
}

export function createDefaultInitialState(
  params: TunableParameters,
  aeroTable: AeroPerformanceTable,
  options: SimulationInitialStateOptions = {},
): TurbineState {
  const rotorSpeedRadPerSec =
    options.rotorSpeedRadPerSec ?? params.ratedRotorSpeedRadPerSec;

  const platformPitchRateRadPerSec =
    options.platformPitchRateRadPerSec ?? 0;

  let platformPitchRad = options.platformPitchRad;

  if (platformPitchRad === undefined) {
    assertPositiveFinite(
      "platformPitchStiffnessNm",
      params.platformPitchStiffnessNm,
    );

    const equilibriumWindSpeedMps =
      options.equilibriumWindSpeedMps ?? params.ratedWindSpeedMps;

    const equilibriumPitchRad =
      options.equilibriumPitchRad ?? params.trimPitchRad;

    const initialAero = computeAerodynamicOutputs(
      aeroTable,
      {
        rotorSpeedRadPerSec,
        pitchRad: equilibriumPitchRad,
        windSpeedMps: equilibriumWindSpeedMps,
      },
      {
        airDensityKgPerM3: params.airDensityKgPerM3,
        rotorRadiusM: params.rotorRadiusM,
      },
    );

    platformPitchRad =
      (params.thrustToPitchMomentArmM * initialAero.thrustN) /
      params.platformPitchStiffnessNm;
  }

  return {
    timeS: options.timeS ?? 0,
    rotorSpeedRadPerSec,
    rotorAzimuthRad: options.rotorAzimuthRad ?? 0,
    platformPitchRad,
    platformPitchRateRadPerSec,
  };
}

export function runSimulationScenario(
  args: RunSimulationScenarioArgs,
): SimulationScenarioResult {
  const { scenario, params, aeroTable } = args;

  validateScenario(scenario);

  const nSteps = getSimulationStepCount(scenario.totalTimeS, scenario.dtS);
  const wind = createWindDisturbance(scenario.wind);

  const initialPitchRad = getInitialPitchRad(scenario, params);
  let state = createDefaultInitialState(params, aeroTable, {
    ...scenario.initialState,
    equilibriumWindSpeedMps:
      scenario.initialState?.equilibriumWindSpeedMps ??
      getNominalInitialWindSpeedMps(scenario.wind),
    equilibriumPitchRad:
      scenario.initialState?.equilibriumPitchRad ?? initialPitchRad,
  });

  let windSample = getWindDisturbanceSample(wind);
  let controllerState = createScenarioControllerState(scenario, params);
  let currentControl = createInitialControl(scenario, params, controllerState);
  let currentControllerDiagnostics: PitchControllerDiagnostics | undefined;

  const samples: SimulationScenarioSample[] = [];

  for (let iStep = 0; iStep <= nSteps; iStep += 1) {
    samples.push(
      createSimulationSample({
        state,
        control: currentControl,
        windSample,
        params,
        aeroTable,
        controllerDiagnostics: currentControllerDiagnostics,
      }),
    );

    if (iStep === nSteps) {
      break;
    }

    if (scenario.controller.mode === "closed-loop-pitch-pi") {
      if (controllerState === undefined) {
        throw new Error(
          "Internal error: closed-loop scenario has no controller state.",
        );
      }

      const controllerConfig =
        scenario.controller.config ?? createPitchControllerConfig(params);

      const controllerResult = stepPitchController(
        controllerState,
        {
          rotorSpeedRadPerSec: state.rotorSpeedRadPerSec,
          platformPitchRateRadPerSec: state.platformPitchRateRadPerSec,
        },
        controllerConfig,
        scenario.dtS,
      );

      controllerState = controllerResult.state;
      currentControl = controllerResult.control;
      currentControllerDiagnostics = controllerResult.diagnostics;
    } else {
      currentControl = scenario.controller.fixedControl;
      currentControllerDiagnostics = undefined;
    }

    windSample = stepWindDisturbance(wind, scenario.dtS);

    const snapshot = stepSimulation(
      state,
      windSample.environment,
      currentControl,
      params,
      aeroTable,
      { dtS: scenario.dtS },
    );

    state = snapshot.state;
  }

  return {
    scenario,
    samples,
    finalState: state,
  };
}

export function getExpectedSimulationSampleCount(
  totalTimeS: number,
  dtS: number,
): number {
  return getSimulationStepCount(totalTimeS, dtS) + 1;
}

function createScenarioControllerState(
  scenario: SimulationScenarioConfig,
  params: TunableParameters,
): PitchControllerState | undefined {
  if (scenario.controller.mode !== "closed-loop-pitch-pi") {
    return undefined;
  }

  if (scenario.controller.initialControllerState !== undefined) {
    return scenario.controller.initialControllerState;
  }

  const controllerConfig =
    scenario.controller.config ?? createPitchControllerConfig(params);

  return createPitchControllerState(
    controllerConfig,
    scenario.controller.initialPitchRad ?? controllerConfig.trimPitchRad,
  );
}

function createInitialControl(
  scenario: SimulationScenarioConfig,
  params: TunableParameters,
  controllerState: PitchControllerState | undefined,
): ControlInputs {
  if (scenario.controller.mode === "open-loop-fixed") {
    return scenario.controller.fixedControl;
  }

  const controllerConfig =
    scenario.controller.config ?? createPitchControllerConfig(params);

  return {
    collectivePitchRad:
      controllerState?.previousPitchRad ??
      scenario.controller.initialPitchRad ??
      controllerConfig.trimPitchRad,
    generatorTorqueNm: controllerConfig.generatorTorqueNm,
  };
}

function getInitialPitchRad(
  scenario: SimulationScenarioConfig,
  params: TunableParameters,
): number {
  if (scenario.controller.mode === "open-loop-fixed") {
    return scenario.controller.fixedControl.collectivePitchRad;
  }

  return (
    scenario.controller.initialPitchRad ??
    scenario.controller.config?.trimPitchRad ??
    params.trimPitchRad
  );
}

function createSimulationSample(args: {
  state: TurbineState;
  control: ControlInputs;
  windSample: WindDisturbanceSample;
  params: TunableParameters;
  aeroTable: AeroPerformanceTable;
  controllerDiagnostics?: PitchControllerDiagnostics;
}): SimulationScenarioSample {
  const { state, control, windSample, params, aeroTable } = args;

  const relativeWind = computeRelativeWind(
    state,
    windSample.environment,
    params,
  );

  const aero = computeAerodynamicOutputs(
    aeroTable,
    {
      rotorSpeedRadPerSec: state.rotorSpeedRadPerSec,
      pitchRad: control.collectivePitchRad,
      windSpeedMps: relativeWind.effectiveWindSpeedMps,
    },
    {
      airDensityKgPerM3: params.airDensityKgPerM3,
      rotorRadiusM: params.rotorRadiusM,
    },
  );

  return {
    timeS: state.timeS,

    windSpeedMps: windSample.windSpeedMps,
    meanWindSpeedMps: windSample.meanWindSpeedMps,
    gustMps: windSample.gustMps,
    turbulentMps: windSample.turbulentMps,
    effectiveWindSpeedMps: relativeWind.effectiveWindSpeedMps,
    projectedWindSpeedMps: relativeWind.projectedWindSpeedMps,
    platformVelocityWindCorrectionMps:
      relativeWind.platformVelocityWindCorrectionMps,
    rotorTiltRad: relativeWind.rotorTiltRad,
    rotorNormalProjectionFactor: relativeWind.rotorNormalProjectionFactor,
    rotorSpeedRadPerSec: state.rotorSpeedRadPerSec,
    rotorAzimuthRad: state.rotorAzimuthRad,

    collectivePitchRad: control.collectivePitchRad,
    generatorTorqueNm: control.generatorTorqueNm,

    platformPitchRad: state.platformPitchRad,
    platformPitchRateRadPerSec: state.platformPitchRateRadPerSec,

    aerodynamicPowerW: aero.powerW,
    aerodynamicTorqueNm: aero.torqueNm,
    thrustN: aero.thrustN,
    cp: aero.cp,
    ct: aero.ct,

    wavePitchMomentNm: windSample.environment.wavePitchMomentNm,

    controllerDiagnostics: args.controllerDiagnostics,
  };
}

function getNominalInitialWindSpeedMps(
  windConfig: WindDisturbanceConfig,
): number {
  if (windConfig.mode === "turbulent" && windConfig.initialWindSpeedMps !== undefined) {
    return windConfig.initialWindSpeedMps;
  }

  return windConfig.meanWindSpeedMps;
}

function validateScenario(scenario: SimulationScenarioConfig): void {
  if (scenario.name.trim().length === 0) {
    throw new Error("Simulation scenario name must not be empty.");
  }

  assertPositiveFinite("dtS", scenario.dtS);

  if (!Number.isFinite(scenario.totalTimeS) || scenario.totalTimeS < 0) {
    throw new Error(
      `totalTimeS must be finite and non-negative. Received ${scenario.totalTimeS}.`,
    );
  }

  getSimulationStepCount(scenario.totalTimeS, scenario.dtS);

  if (scenario.controller.mode === "open-loop-fixed") {
    assertFiniteControl(scenario.controller.fixedControl);
  }
}

function getSimulationStepCount(totalTimeS: number, dtS: number): number {
  assertPositiveFinite("dtS", dtS);

  if (!Number.isFinite(totalTimeS) || totalTimeS < 0) {
    throw new Error(
      `totalTimeS must be finite and non-negative. Received ${totalTimeS}.`,
    );
  }

  const nSteps = Math.round(totalTimeS / dtS);
  const reconstructedTotalTimeS = nSteps * dtS;

  if (Math.abs(reconstructedTotalTimeS - totalTimeS) > 1e-9) {
    throw new Error(
      `totalTimeS (${totalTimeS}) must be an integer multiple of dtS (${dtS}).`,
    );
  }

  return nSteps;
}

function assertFiniteControl(control: ControlInputs): void {
  assertFinite("fixedControl.collectivePitchRad", control.collectivePitchRad);
  assertFinite("fixedControl.generatorTorqueNm", control.generatorTorqueNm);
}

function assertPositiveFinite(name: string, value: number): void {
  if (!Number.isFinite(value) || value <= 0) {
    throw new Error(`${name} must be a positive finite number. Received ${value}.`);
  }
}

function assertFinite(name: string, value: number): void {
  if (!Number.isFinite(value)) {
    throw new Error(`${name} must be finite. Received ${value}.`);
  }
}